# Use an official Node runtime as a base image
FROM node:20.4.0

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install any dependencies
RUN npm install

# Copy the rest of your application's code
COPY . .

# expose a port
EXPOSE 8080

# Your application's default command
CMD ["node", "worker.js"]
